config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from tayo import views

urlpatterns = [
    path('', views.main, name='main'),
    path("admin/", admin.site.urls),
    path("iot/", include('iot.urls')),
    path("tayo/", include('tayo.urls')),
    path('common/', include('common.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iot/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'iot'

urlpatterns = [
    path('upload/', upload, name='upload'),
    path('sec_file/', SecFileListView.as_view(), name='list'),
    path('sec_file/<int:pk>', SecFileDetailView.as_view(), name='detail'),
]

tayo/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView
from . import views

app_name = 'tayo'

urlpatterns = [
    path('main/', views.main, name='main'),

    path('reserve/', views.reserve, name='reserve'),
    path('reserve/add', views.reserve_add, name='reserve_add'),

    path('info/', views.info, name='info'),
    path('parking/', views.parking, name='parking'),
]

common/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models

class UserManager(BaseUserManager):
    """
    BaseUserManager에서 정보 가져와서 필요한 부분 수정
    """
    def create_user(self, email, car_number, phone_number, password=None):
        if not phone_number:
            raise ValueError('must have user email')
        if not email:
            raise ValueError('must have user email')
        user = self.model(
            phone_number=phone_number,
            email=self.normalize_email(email),
            car_number=car_number,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, car_number, phone_number,password):
        user = self.create_user(
            phone_number=phone_number,
            password=password,
            email=self.normalize_email(email),
            car_number=car_number,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    """
    실제 생성할 User 테이블 설정, 위에 만든 UserManager 참고함

    phone_number : 전화번호, 최대길이 20, 중복불가, - 없이 입력
    email : 이메일, 최대길이 255, 중복불가, 이메일 형식 지켜야함
    car_number : 차량번호, 최대길이 20, 공백없음 + replace(" ", "")으로 공백제거
    """
    phone_number = models.CharField(max_length=20,unique=True)
    email = models.EmailField(max_length=255,unique=True)
    car_number = models.CharField(max_length=20)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email','car_number','parking_number']
    
    def __str__(self):
        return self.phone_number

    def to_json(self):
        return {
            "id" : self.id,
            "phone_number" : self.phone_number,
            "email" : self.email,
            "car_number" : self.car_number,
        }
        
def has_perm(self, perm, obj=None):
    """
    True를 반환하여 권한이 있음을 알림
    Ojbect를 반환하는 경우 해당 Object로 사용 권한을 확인하는 절차가 필요
    """
    return True

def has_module_perms(self, app_label):
    """
    True를 반환하여 주어진 앱(App)의 모델(Model)에 접근 가능하도록 함
    """
    return True

@property
def is_staff(self):
    """
    True가 반환되면 장고(django)의 관리자 화면에 로그인 할 수 있음
    """
    return self.is_admin


class Parking(models.Model):
    """
    주차공간 테이블 생성

    parking_number : 주차공간번호, 자동추가필드(인덱스), 기본키(=NULL안됨, 중복안됨)
    lat : 위도, 최대길이 20
    lon : 경도, 최대길이 20
    res_state : 예약가능상태, 최대길이 20, ON/OFF로 상태 표기
    detail_add : 상세주소, 최대길이 255, NULL 저장 가능, 폼 양식 비우기 가능
    finish_car_number : 등록된 차량번호, 최대길이 20, NULL 저장 가능
    parking_car_number : 주차된 차량번호, 최대길이 20, NULL 저장 가능
    """
    parking_number = models.AutoField(primary_key=True)
    parking_name = models.CharField(max_length=20)
    lat = models.CharField(max_length=20)
    lon = models.CharField(max_length=20)
    res_state = models.CharField(max_length=20)
    detail_add = models.CharField(max_length=255, null=True, blank=True)
    finish_car_number = models.CharField(max_length=20, null=True, blank=True)
    owner = models.ForeignKey("User", on_delete=models.CASCADE, db_column='owner') # user모델에서 parking_set로 관계 생김

    def to_json(self):
        return {
            "parking_number" : self.parking_number,
            "parking_name" : self.parking_name,
            "lat" : self.lat,
            "lon" : self.lon,
            "res_state" : self.res_state,
            "detail_add" : self.detail_add,
            "finish_car_number" : self.finish_car_number,
            "owner" : self.owner
        }



class Res(models.Model):
    """
    예약 테이블 생성

    phone_number : 전화번호, 외래키, User 테이블과 연결
    """
    user_id = models.ForeignKey("User", on_delete=models.SET_NULL, db_column='user_id', null=True, blank=True)
    parking_number = models.ForeignKey("Parking", on_delete=models.SET_NULL, db_column='parking_number', null=True, blank=True)
    time = models.CharField(max_length=20)
    start_time = models.DateTimeField(max_length=100)
    end_time = models.DateTimeField(max_length=100)
    res_car_number = models.CharField(max_length=20)

    def to_json(self):
        return {
            "id" : self.id,
            "user_id" : self.user_id,
            "parking_number" : self.parking_number,
            "time" : self.time,
            "start_time" : self.start_time,
            "end_time" : self.end_time,
            "res_car_number" : self.res_car_number
        }

tayo/models.py
from django.db import models

# Create your models here.

tayo/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from common.models import User, Parking, Res


class ResForm(forms.ModelForm):
    class Meta:
        model = Res
        fields = ('id', 'time', 'res_car_number', 'parking_number')

tayo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from common.models import Parking, Res
from django.contrib.auth.decorators import login_required
from .forms import ResForm
from datetime import datetime, timedelta

def main(request):
    return render(request, 'tayo/main.html')

def reserve(request):
    """
    예약하기
    """
    # 전체 주차장 리스트 불러오기
    parking_list = Parking.objects.all()
    res_list = Res.objects.all()

    # context에 담아서 tayo/reserve.html에 전송
    context ={
        'parking_list' : parking_list,
        'res_list' : res_list
    }
    return render(request, 'tayo/reserve.html', context)

@login_required(login_url='common:login')
def reserve_add(request):
    """
    예약 추가
    """
    if request.method == 'POST':
        form = ResForm(request.POST)
        if form.is_valid():
            res = form.save(commit=False)
            res.start_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            res.end_time = (datetime.now() + timedelta(hours=int(request.POST['time']))).strftime("%Y-%m-%d %H:%M:%S")
            res.user_id = request.user
            res.save()

            return redirect('common:myreserve')
    else:
        form = ResForm()

    
    context={
        'form':form,
    }

    return render(request, 'tayo/reserve.html', context)


def info(request):
    return render(request, 'tayo/info.html')

def parking(request):
    # 전체 주차장 리스트 불러오기
    parking_list = Parking.objects.all()

    # context에 담아서 tayo/reserve.html에 전송
    context ={
        'parking_list' : parking_list
    }
    return render(request, 'tayo/parking.html', context)

templates/tayo/info.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="en">
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      {% include 'navbar.html'%}
      <div class="android-content mdl-layout__content">
        <a name="top"></a>
        <div class="nv-page-title-wrap nv-big-title">
          <div class="android-customized-section mdl-typography--text-center">
            <div class="nv-page-title">
              <h1> 이용 방법 </h1>
              <hr style="border: solid 0.1px Gainsboro;"/>
              <div class="logo-font android-sub-slogan">  주택, 빌라, 상가 주차장 등 개인이 소유한 주차공간을 타요타요에서 다른 사람에게 공유할 수 있습니다.</div><br/><br/><br/><br/>
              <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/step1.png" style="max-width:100%; height:auto;"/>
              <br/>
              <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/res1.png" style="max-width:100%; height:auto;"/>
              <br/>
              <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/res2.png" style="max-width:100%; height:auto;"/>
              <br/>
              <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/step2.png" style="max-width:100%; height:auto;"/>
              <br/>
              <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/lot1.png" style="max-width:100%; height:auto;"/>
              <br/>
              <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/lot2.png" style="max-width:100%; height:auto;"/>
              <br/>
              <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/step3.png" style="max-width:100%; height:auto;"/>
              <br/>
              <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/check1.png" style="max-width:100%; height:auto;"/>
            </div>
            <br/>
            <br/>
          </div>
        </div>
        {% include 'footer.html'%}
      </div>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>
{% endblock %}

templates/tayo/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="en">
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      {% include 'navbar.html'%} 
      <div class="android-content mdl-layout__content">
        <a name="top"></a>
        <div class="android-customized-section mdl-typography--text-center">
          <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/parking3.png" style="max-width:100%; height:auto;"/>
          <div class="logo-font android-slogan">지정주차 센서시스템</div> 
            </br>
            <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/device.png" style="max-width:100%; height:auto;" />
            </br>
          </p>
            </br>
            </br>
            <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/space.png" style="max-width:100%; height:auto;" />
            </br>
            </br>
          </p>
            </br>
            <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/alram.png" style="max-width:100%; height:auto;" />
          </p>
        </div>
        <div class="android-customized-section">
          <div class="android-customized-section-text">
            <div class="mdl-typography--font-light mdl-typography--display-1-color-contrast"></div>
            <p class="mdl-typography--font-light"></p>
        </div>
        <div class="android-more-section">
          <div class="android-section-title mdl-typography--display-1-color-contrast">당일주차 | 주차장관리 | 공유주차</div>
          <div class="android-card-container mdl-grid">
            <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-card mdl-shadow--3dp">
              <div class="mdl-card__media">
                
              </div>
              <div class="mdl-card__title">
                 <h4 class="mdl-card__title-text">주차 정보 한눈에</h4>
              </div>
              <div class="mdl-card__supporting-text">
                <span class="mdl-typography--font-light mdl-typography--subhead">자세한 주차장 위치, 주차가능한지 on/off 정보를  확인할 수 있어요.</span>
              </div>
              <div class="mdl-card__actions">
                 <a class="android-link mdl-button mdl-js-button mdl-typography--text-uppercase" href=""></a>
              </div>
            </div>
            <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-card mdl-shadow--3dp">
              <div class="mdl-card__media">
              </div>
              <div class="mdl-card__title">
                 <h4 class="mdl-card__title-text">편리한 검색</h4>
              </div>
              <div class="mdl-card__supporting-text">
                <span class="mdl-typography--font-light mdl-typography--subhead">내목적지에 맞는 주차 정보를 지도를 통해 쉽게 찾을 수 있어요. </span>
              </div>
              <div class="mdl-card__actions">
              </div>
            </div>

            <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-card mdl-shadow--3dp">
              <div class="mdl-card__media">
              </div>
              <div class="mdl-card__title">
                 <h4 class="mdl-card__title-text">부정주차 문제 해결</h4>
              </div>
              <div class="mdl-card__supporting-text">
                <span class="mdl-typography--font-light mdl-typography--subhead">등록되지 않는 차량이 주차할 시 거주자는 문자알림을 통해 확인할 수 있어요.</span>
              </div>
              <div class="mdl-card__actions">
              </div>
            </div>

            <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-card mdl-shadow--3dp">
              <div class="mdl-card__media">
              </div>
              <div class="mdl-card__title">
                <h4 class="mdl-card__title-text">주차공간 해결</h4>
              </div>
              <div class="mdl-card__supporting-text">
                <span class="mdl-typography--font-light mdl-typography--subhead">주거지전용 빈 주차장을 공유함으로써 주차공간을 함께 이용할 수 있어요.</span>
              </div>
              <div class="mdl-card__actions">
              </div>
            </div>
          </div>
          <div class="android-customized-section">
            <div class="android-customized-section-text">
              <img class="android-screen-image" href="{% url 'tayo:main'%}" src="../../static/images/sss.png" style="max-width:100%; height:auto;" />
              <div class="mdl-typography--font-light mdl-typography--display-1-color-contrast"></div>
              <p class="mdl-typography--font-light"></p>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
  {% include 'footer.html'%}
</html>

{% endblock %}

templates/tayo/parking.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="en">
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      {% include 'navbar.html'%} 
      <div class="android-content mdl-layout__content">
        <a name="top"></a>
        <div class="android-customized-section mdl-typography--text-center" style="margin-top:-5%">
          <div class="logo-font android-slogan">
            주차장현황</br></br>
          </div>
          <center style=""><div id="map" style="width:60%;height:550px;"></div></center>
        </div></br></br>
        {% include 'footer.html'%}
      </div>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
  
</html>
{% endblock %}
{% block script%}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=ce903cdfbeb38247132d86bac3923a8b"></script>
<script>
  var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new kakao.maps.LatLng(37.528195, 126.984208), // 지도의 중심좌표
        level: 8 // 지도의 확대 레벨
    };

  var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

  var positions = [
    {% for i in parking_list.all %}
      {
        content : '<span class="info-title">'+'{{i.parking_name}}'+'</span>',
        latlng : new kakao.maps.LatLng({{i.lat}}, {{i.lon}})
      },
    {% endfor %}
  ]

  for (var i = 0; i < positions.length; i ++){
    var marker = new kakao.maps.Marker({
      map: map, // 마커를 표시할 지도
      position: positions[i].latlng // 마커의 위치
    });

    // 마커에 표시할 인포윈도우를 생성합니다 
    var infowindow = new kakao.maps.InfoWindow({
      content: positions[i].content // 인포윈도우에 표시할 내용
    });

    kakao.maps.event.addListener(marker, 'mouseover', makeOverListener(map, marker, infowindow));
    kakao.maps.event.addListener(marker, 'mouseout', makeOutListener(infowindow));
  }

  // 인포윈도우를 표시하는 클로저를 만드는 함수입니다 
  function makeOverListener(map, marker, infowindow) {
    return function() {
        infowindow.open(map, marker);
    };
  }

  // 인포윈도우를 닫는 클로저를 만드는 함수입니다 
  function makeOutListener(infowindow) {
    return function() {
        infowindow.close();
    };
  }

</script>
{% endblock%}

templates/tayo/reserve.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="en">
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      {% include 'navbar.html'%} 
      <div class="android-content mdl-layout__content">
        <a name="top"></a>
        </br>
        </br>
        <div class="android-be-customized-section mdl-typography--text-center" style="display:flex;justify-content:center;align-items:center;top:30%;">
          <div class="demo-card-wide mdl-card mdl-shadow--2dp" style="align-items:center; width:80%;">
            <div class="mdl-card__title">
              <h2 class="mdl-card__title-text">주차장 예약하기</h2>
            </div>
            <div class="mdl-card__supporting-text">
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <form method="post" action="{% url 'tayo:reserve_add' %}" class="post-form" autocomplete="off">
                  {% csrf_token %}
                  {% include 'form_errors.html'%}</br>
                  주차시간을 선택해주세요</br></br>
                  <select id="time" name="time" value="">
                    <option value="1" selected>1시간</option>
                    <option value="2">2시간</option>
                    <option value="3">3시간</option>
                    <option value="4">4시간</option>
                    <option value="5">5시간</option>
                  </select></br></br></br>
                  주차장을 선택해주세요</br></br>
                  <div id="map" style="width:100%;height:350px;"></div></br>
                  <p id="result" name="result"></p></br>
                  <input type="hidden" id="parking_number" name="parking_number" value=""></input>
                  차량번호를 입력해주세요
                  <input type="text" class="mdl-textfield__input" id="res_car_number" name="res_car_number" value=""></input>
                  </br></br>
                  <button id="reserve_btn" type="submit" style="position:static" onclick="location.href='{% url 'tayo:reserve' %}'" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                    예약하기
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        </br></br>
        {% include 'footer.html'%} 
      </div>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>
{% endblock %}
{% block script %}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=ce903cdfbeb38247132d86bac3923a8b"></script>
<script>
  // 1. 지도 생성하기
  var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
		    mapOption = {
		        center: new kakao.maps.LatLng(37.528195, 126.984208), // 지도의 중심좌표
		        level: 8, // 지도의 확대 레벨
		        mapTypeId : kakao.maps.MapTypeId.ROADMAP // 지도종류
		    }; 

	// 지도를 생성한다 
	var map = new kakao.maps.Map(mapContainer, mapOption); 

  // 1. 끝

  // 2. 현재 위치 불러오기
  // 미완성
  // 2. 끝

  // 3. DB에 저장된 주차장 모두 불러오기
  var positions = [
    {% for i in parking_list.all %}
      {
        content : '<span class="info-title">'+'{{i.parking_name}}'+'</span>',
        latlng : new kakao.maps.LatLng({{i.lat}}, {{i.lon}}),
        parking_number : '{{i.parking_number}}',
        parking_name : '{{i.parking_name}}',
        owner : '{{i.owner}}'
      },
    {% endfor %}
  ]

  for (var i = 0; i< positions.length; i++){
    //마커 생성
    var marker = new kakao.maps.Marker({
      position : positions[i].latlng
    });
    marker.setClickable(true);
    marker.setMap(map);

    // 마커를 클릭했을 때 마커 위에 표시할 인포윈도우를 생성합니다
    var iwContent = '<div style="padding:5px;">'+positions[i].parking_name+'</div>', // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다
    iwRemoveable = true; // removeable 속성을 ture 로 설정하면 인포윈도우를 닫을 수 있는 x버튼이 표시됩니다

    // 인포윈도우를 생성합니다
    var infowindow = new kakao.maps.InfoWindow({
    content : iwContent,
    removable : iwRemoveable
    });

    var count= i;

    // 마커에 클릭이벤트를 등록합니다
    kakao.maps.event.addListener(marker, 'click', makeAddListener(map, marker, infowindow, count));
  }

  //클릭이벤트
  function makeAddListener(map, marker, infowindow, count){
    return function(){
      infowindow.open(map, marker);

      if(positions[count].owner == '{{request.user}}'){
        var message = "본인의 주차장은 예약할 수 없습니다.";
        $("#reserve_btn").attr("disabled", true);
      }
      else{
        var message = "선택한 주차장은 " + positions[count].parking_name + '입니다.';
        $("#reserve_btn").attr("disabled", false);
      }

      var resultDiv = document.getElementById('result'); 
      resultDiv.innerHTML = message;
      var numberDiv = document.getElementById('parking_number'); 
      numberDiv.value = positions[count].parking_number;
      
    };
  };
  // 3. 끝



</script>
{% endblock %}