config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from tayo import views

urlpatterns = [
    path('', views.main, name='main'),
    path("admin/", admin.site.urls),
    path("iot/", include('iot.urls')),
    path("tayo/", include('tayo.urls')),
    path('common/', include('common.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iot/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'iot'

urlpatterns = [
    path('upload/', upload, name='upload'),
    path('sec_file/', SecFileListView.as_view(), name='list'),
    path('sec_file/<int:pk>', SecFileDetailView.as_view(), name='detail'),
]

iot/models.py
from django.db import models

# 녹화파일 업로드
class SecFile(models.Model):
    file_name = models.CharField(max_length=100)
    sec_file = models.FileField(upload_to="")

iot/views.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import SecFile
from django.views import generic

# request.method가 POST로 오면 파일 저장
# 성공시 success 출력, 실패시 fail 출력
@csrf_exempt
def upload(request):
    if request.method == 'POST':
        file_name = request.POST['file_name']
        sec_file =  request.FILES['sec_file']
        model = SecFile(file_name = file_name, sec_file = sec_file)
        model.save()
        
        print('upload_file', file_name, sec_file)
        msg = { 'result' : 'success'}
    
    else:
        msg = { 'result' : 'fail'}
    
    return JsonResponse(msg)

# 저장된 파일 리스트 확인하는 클래스
class SecFileListView(generic.ListView):
    model = SecFile
    template_name = 'iot/sec_file_list.html'
    context_object_name = 'sec_files'


# 저장된 파일 열어보기
class SecFileDetailView(generic.DetailView):
    model = SecFile
    template_name = 'iot/sec_file_detail.html'
    context_object_name = 'imgfile'

templates/iot/sec_file_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="padding:3vh;"></div>
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="card align-middle" style="width:100rem; border-radius:20px; border-color:brown;">
                <div class="card-title" style="margin-top:30px;">    
                    <h2 class="card-title text-center">{{imgfile.file_name}}</h2>
                </div>
                <div class="card-body text-center">
                    <img src="/media/{{imgfile.sec_file }}" type="jpg" />
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/iot/sec_file_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="padding:3vh;"></div>
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="card align-middle" style="width:100rem; border-radius:20px; border-color:brown;">
                <div class="card-title" style="margin-top:30px;">    
                    <h2 class="card-title text-center">수신된 이미지</h2>
                </div>
                <div class="card-body text-center">
                    {% for sec_file in sec_files %}
                        <table>
                            <tr><a href="{% url 'iot:detail' sec_file.id %}">{{ sec_file.file_name }}</a></tr>
                        </table>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}