common/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('mypage/', views.mypage, name='mypage'),
    path('mypage/<int:parking_number>/', views.mypage_detail, name="mypage_detail"),
    path('mypage/<int:parking_number>/modify/', views.parking_modify, name='parking_modify'),
    
    path('add/', views.add, name='add'),
    path('add/parking', views.parking_add, name='parking_add'),

    path('myreserve/', views.myreserve , name="myreserve"),
    path('myreserve/delete/<int:res_id>', views.myreserve_delete, name='myreserve_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from tayo import views

urlpatterns = [
    path('', views.main, name='main'),
    path("admin/", admin.site.urls),
    path("iot/", include('iot.urls')),
    path("tayo/", include('tayo.urls')),
    path('common/', include('common.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iot/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'iot'

urlpatterns = [
    path('upload/', upload, name='upload'),
    path('sec_file/', SecFileListView.as_view(), name='list'),
    path('sec_file/<int:pk>', SecFileDetailView.as_view(), name='detail'),
]

common/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models

class UserManager(BaseUserManager):
    """
    BaseUserManager에서 정보 가져와서 필요한 부분 수정
    """
    def create_user(self, email, car_number, phone_number, password=None):
        if not phone_number:
            raise ValueError('must have user email')
        if not email:
            raise ValueError('must have user email')
        user = self.model(
            phone_number=phone_number,
            email=self.normalize_email(email),
            car_number=car_number,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, car_number, phone_number,password):
        user = self.create_user(
            phone_number=phone_number,
            password=password,
            email=self.normalize_email(email),
            car_number=car_number,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    """
    실제 생성할 User 테이블 설정, 위에 만든 UserManager 참고함

    phone_number : 전화번호, 최대길이 20, 중복불가, - 없이 입력
    email : 이메일, 최대길이 255, 중복불가, 이메일 형식 지켜야함
    car_number : 차량번호, 최대길이 20, 공백없음 + replace(" ", "")으로 공백제거
    """
    phone_number = models.CharField(max_length=20,unique=True)
    email = models.EmailField(max_length=255,unique=True)
    car_number = models.CharField(max_length=20)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email','car_number','parking_number']
    
    def __str__(self):
        return self.phone_number

    def to_json(self):
        return {
            "id" : self.id,
            "phone_number" : self.phone_number,
            "email" : self.email,
            "car_number" : self.car_number,
        }
        
def has_perm(self, perm, obj=None):
    """
    True를 반환하여 권한이 있음을 알림
    Ojbect를 반환하는 경우 해당 Object로 사용 권한을 확인하는 절차가 필요
    """
    return True

def has_module_perms(self, app_label):
    """
    True를 반환하여 주어진 앱(App)의 모델(Model)에 접근 가능하도록 함
    """
    return True

@property
def is_staff(self):
    """
    True가 반환되면 장고(django)의 관리자 화면에 로그인 할 수 있음
    """
    return self.is_admin


class Parking(models.Model):
    """
    주차공간 테이블 생성

    parking_number : 주차공간번호, 자동추가필드(인덱스), 기본키(=NULL안됨, 중복안됨)
    lat : 위도, 최대길이 20
    lon : 경도, 최대길이 20
    res_state : 예약가능상태, 최대길이 20, ON/OFF로 상태 표기
    detail_add : 상세주소, 최대길이 255, NULL 저장 가능, 폼 양식 비우기 가능
    finish_car_number : 등록된 차량번호, 최대길이 20, NULL 저장 가능
    parking_car_number : 주차된 차량번호, 최대길이 20, NULL 저장 가능
    """
    parking_number = models.AutoField(primary_key=True)
    parking_name = models.CharField(max_length=20)
    lat = models.CharField(max_length=20)
    lon = models.CharField(max_length=20)
    res_state = models.CharField(max_length=20)
    detail_add = models.CharField(max_length=255, null=True, blank=True)
    finish_car_number = models.CharField(max_length=20, null=True, blank=True)
    owner = models.ForeignKey("User", on_delete=models.CASCADE, db_column='owner') # user모델에서 parking_set로 관계 생김

    def to_json(self):
        return {
            "parking_number" : self.parking_number,
            "parking_name" : self.parking_name,
            "lat" : self.lat,
            "lon" : self.lon,
            "res_state" : self.res_state,
            "detail_add" : self.detail_add,
            "finish_car_number" : self.finish_car_number,
            "owner" : self.owner
        }



class Res(models.Model):
    """
    예약 테이블 생성

    phone_number : 전화번호, 외래키, User 테이블과 연결
    """
    user_id = models.ForeignKey("User", on_delete=models.SET_NULL, db_column='user_id', null=True, blank=True)
    parking_number = models.ForeignKey("Parking", on_delete=models.SET_NULL, db_column='parking_number', null=True, blank=True)
    time = models.CharField(max_length=20)
    start_time = models.DateTimeField(max_length=100)
    end_time = models.DateTimeField(max_length=100)
    res_car_number = models.CharField(max_length=20)

    def to_json(self):
        return {
            "id" : self.id,
            "user_id" : self.user_id,
            "parking_number" : self.parking_number,
            "time" : self.time,
            "start_time" : self.start_time,
            "end_time" : self.end_time,
            "res_car_number" : self.res_car_number
        }

common/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User
from .models import Parking

"""
기존 클래스
class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")
"""

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation',widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('phone_number','email','car_number')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self,commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('phone_number','email','car_number')

    def clean_password(self):
        return self.initial["password"]


class ParkingCreateForm(forms.ModelForm):
    class Meta:
        model = Parking
        fields = ('parking_number', 'parking_name', 'lat', 'lon', 'res_state', 'detail_add', 'finish_car_number')

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404
from common.forms import UserCreationForm, UserChangeForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Parking, Res
from .forms import ParkingCreateForm
import json

def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            raw_password = form.cleaned_data.get('password1')
            phone_number = form.cleaned_data.get('phone_number')
            user = authenticate(password=raw_password, phone_number=phone_number)
            login(request, user)
            return redirect('main')
    else:
        form = UserCreationForm()
    return render(request, 'common/signup.html', {'form': form})


def mypage(request):
    return render(request, 'common/mypage.html')

def add(request):
    return render(request, 'common/add.html')

@login_required(login_url='common:login')
def myreserve(request):
    """
    나의 예약현황 출력
    """
    # 선택한 주차장 예약 리스트
    res = Res.objects.filter(user_id=request.user)

    context={
        'res':res,
    }

    return render(request, 'common/myreserve.html', context)

@login_required(login_url='common:login')
def myreserve_delete(request, res_id):
    """
    나의 예약현황에서 선택 행 삭제
    """
    delete_res = get_object_or_404(Res, pk=res_id)
    delete_res.delete()

    return redirect('/common/myreserve')

@login_required(login_url='common:login')
def parking_add(request):
    """
    parking 테이블에 값 추가
    """
    if request.method == 'POST':
        form = ParkingCreateForm(request.POST)
        if form.is_valid():
            parking = form.save(commit=False)
            parking.owner = request.user
            parking.save()

            return redirect('common:mypage')
    else:
        form = ParkingCreateForm()

    
    context={
        'form':form,
    }

    return render(request, 'common/add.html', context)

@login_required(login_url='common:login')
def mypage_detail(request, parking_number):
    """
    주차장 관리 출력
    """
    # 선택한 주차장 리스트
    parking_user = get_object_or_404(Parking, pk=parking_number)
    # 선택한 주차장 예약 리스트
    parking_res = Res.objects.filter(parking_number=parking_number)
    
    context = { 'parking_user' : parking_user, 'parking_res' : parking_res }

    return render(request, 'common/mypage_detail.html', context)


@login_required(login_url='common:login')
def parking_modify(request, parking_number):
    """
    parking 테이블 값 수정
    """
    parking_on = Parking.objects.get(parking_number=parking_number)

    if parking_on.res_state == "ON":
        parking_on.res_state = "OFF"
        parking_on.save()
    else:
        parking_on.res_state = "ON"
        parking_on.save()

    return redirect(f'/common/mypage/{parking_number}')

templates/common/add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="en">
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      {% include 'navbar.html'%} 
      <div class="android-content mdl-layout__content">
        <a name="top"></a>
      </br>
      </br>
        <div class="android-be-customized-section mdl-typography--text-center" style="display:flex;justify-content:center;align-items:center;top:30%;">
            <div class="demo-card-wide mdl-card mdl-shadow--2dp" style="align-items:center; width:80%">
                <div class="mdl-card__title">
                    <h2 class="mdl-card__title-text">주차공간 등록하기</h2></br>
                </div>
                <div class="mdl-card__supporting-text">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <form method="post" action="{% url 'common:parking_add' %}" class="post-form" autocomplete="off">
                            {% csrf_token %}
                            {% include 'form_errors.html'%}</br></br>
                            <table>
                                <tbody>
                                    <tr>
                                        <td colspan="2">
                                            <input type="text" class="mdl-textfield__input" id="parking_name" name="parking_name" placeholder="주차공간명"></input></br></br>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td >
                                            <input type="text" class="mdl-textfield__input" id="main_address" placeholder="주소"></input>
                                        </td>
                                        <td>
                                            <input style="position:static; border:none;" type="button" class=" mdl-button mdl-js-button mdl-button--raised mdl-button--colored"onclick="parking_address()" value="검색"></input>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <input type="hidden" id="lat" name="lat" value=""></input>
                                            <input type="hidden" id="lon" name="lon" value=""></input>
                                            <div id="map" style="width:100%;height:300px;"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                        </br>
                                            <input type="text" class="mdl-textfield__input" id="detail_add" name="detail_add" value="" placeholder="상세주소 입력(선택)"></input>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                        </br></br>
                                            등록 즉시 예약이 가능하도록 설정하시겠습니까?
                                        </br></br>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <input type="radio" name="res_state" id="res_state" value="ON">예약가능
                                            <input type="radio" name="res_state" id="res_state" value="OFF" checked="checked">예약불가능
                                        </td>
                                    </tr>
                                </tbody>    
                            </table>
                            </br></br>
                            <button type="submit" style="position:static" onclick="location.href='{% url 'common:mypage' %}'" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                                등록
                            </button>
                        </form>
                    </div>
                </div>
            </div>
          </div>
            </br></br>
          {% include 'footer.html'%}
      </div>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>
{% endblock %}


{% block script%}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=ce903cdfbeb38247132d86bac3923a8b&libraries=services"></script>
<script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
        mapOption = {
            center: new daum.maps.LatLng(37.537187, 127.005476), // 지도의 중심좌표
            level: 5 // 지도의 확대 레벨
        };

    //지도를 미리 생성
    var map = new daum.maps.Map(mapContainer, mapOption);
    //주소-좌표 변환 객체를 생성
    var geocoder = new daum.maps.services.Geocoder();
    //마커를 미리 생성
    var marker = new daum.maps.Marker({
        position: new daum.maps.LatLng(37.537187, 127.005476),
        map: map
    });


    function parking_address() {
        new daum.Postcode({
            oncomplete: function(data) {
                var addr = data.address; // 최종 주소 변수

                // 주소 정보를 해당 필드에 넣는다.
                document.getElementById('main_address').value = addr;
                // 주소로 상세 정보를 검색
                geocoder.addressSearch(data.address, function(results, status) {
                    // 정상적으로 검색이 완료됐으면
                    if (status === daum.maps.services.Status.OK) {

                        var result = results[0]; //첫번째 결과의 값을 활용

                        // 해당 주소에 대한 좌표를 받아서
                        var coords = new daum.maps.LatLng(result.y, result.x);
                        // 지도를 보여준다.
                        mapContainer.style.display = "block";
                        map.relayout();
                        // 지도 중심을 변경한다.
                        map.setCenter(coords);
                        // 마커를 결과값으로 받은 위치로 옮긴다.
                        marker.setPosition(coords);

                        // 위도, 경도 값 input의 value에 추가
                        var lat_value = result.y;
                        var lon_value = result.x;

                        //var resultLat = document.getElementById('lat');
                        //reusltLat.innerHTML = lat_value.toString();
                        document.getElementById('lat').value = lat_value.toString();
                        
                        //var resultLon = document.getElementById('lon');
                        //resultLon.innerHTML = lon_value.toString();
                        document.getElementById('lon').value = lon_value.toString();
                    }
                });
            }
        }).open();
    }
    // 지도에 클릭 이벤트를 등록합니다
    // 지도를 클릭하면 마지막 파라미터로 넘어온 함수를 호출합니다
    kakao.maps.event.addListener(map, 'click', function(mouseEvent) {        
        
        // 클릭한 위도, 경도 정보를 가져옵니다 
        var latlng = mouseEvent.latLng; 
        
        // 마커 위치를 클릭한 위치로 옮깁니다
        marker.setPosition(latlng);
        
        // 위도, 경도 값 input의 value에 추가
        var lat_value = latlng.getLat()
        var lon_value = latlng.getLng()

        //var resultLat = document.getElementById('lat');
        //reusltLat.innerHTML = lat_value.toString();
        document.getElementById('lat').value = lat_value.toString();
        
        //var resultLon = document.getElementById('lon');
        //resultLon.innerHTML = lon_value.toString();
        document.getElementById('lon').value = lon_value.toString();
    
    });

</script>
{% endblock%}

templates/common/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!doctype html>

<html lang="en">
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      {% include 'navbar.html'%} 
      <div class="android-content mdl-layout__content" >
        <a name="top"></a>
        </br>
        </br>
        <div class="android-be-customized-section mdl-typography--text-center" style="display:flex;justify-content:center;align-items:center;top:30%;">
          <div class="demo-card-wide mdl-card mdl-shadow--2dp" style="align-items:center; width:80%">
            <div class="mdl-card__supporting-text">
              <form method="post" class="post-form" action="{% url 'common:login' %}" autocomplete="off">
                {% csrf_token %}
                {% include 'form_errors.html'%}
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                  <input class="mdl-textfield__input" type="text" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
                  <label class="mdl-textfield__label" for="sample3">아이디</label>
                </div>
                </br>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                  <input class="mdl-textfield__input" type="password" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
                  <label class="mdl-textfield__label" for="sample3">비밀번호</label>
                </div>
                </br>
                <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                  로그인
                </button>
              </form>
            </div>
            <div class="mdl-card__actions mdl-card--border">
              <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" href="{% url 'common:signup' %}">
                회원가입
              </a>
            </div>
          </div>
        </div>
      </div>
      {% include 'footer.html'%} 
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>

{% endblock %}

templates/common/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="en">
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      {% include 'navbar.html'%} 
      <div class="android-content mdl-layout__content">
        <a name="top"></a>
        </br>
        </br>
        <div class="android-be-customized-section mdl-typography--text-center" style="display:flex;justify-content:center;align-items:center;top:30%;">
          <div class="demo-card-wide mdl-card mdl-shadow--2dp" style="align-items:center; width:80%">
            <div class="mdl-card__title">
              <h2 class="mdl-card__title-text">{{user.phone_number}}의 마이페이지</h2></br>
            </div>
            <div class="mdl-card__supporting-text">
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp" style="width:100%">
                  <tbody>
                    <tr>
                      <td style="text-align:center">이메일</td>
                      <td>{{user.email}}</td>
                    </tr>
                    <tr>
                      <td style="text-align:center">차량번호</td>
                      <td style="text-align:center">{{user.car_number}}</td>
                    </tr>
                    <tr style="text-align:center">
                      <td style="text-align:center">소유주차공간</td>
                      <td style="text-align:center">
                        {% if user.parking_set.all%}
                          있음
                        {% else %}
                          없음
                        {% endif %}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              </br>
              <button onclick="location.href='{% url 'common:add' %}'" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                주차공간 등록하기
              </button>
            </div>
          </div>
        </div></br></br>
        {% if user.parking_set.all%}
        <div class="android-be-customized-section mdl-typography--text-center" style="display:flex;justify-content:center;align-items:center;top:30%;">
          <div class="demo-card-wide mdl-card mdl-shadow--2dp" style="align-items:center; width:80%">
            <div class="mdl-card__title">
              <h2 class="mdl-card__title-text">주차공간 목록</h2></br>
            </div>
            <div class="mdl-card__supporting-text">
              <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="width:100%">
                <thead>
                  <tr>
                    <th style="text-align:center">번호</th>
                    <th style="text-align:center">이름</th>
                    <th style="text-align:center">예약가능상태</th>
                  </tr>
                </thead>
                <tbody>
                  {% for i in user.parking_set.all %}
                    <tr data-uri="{% url 'common:mypage_detail' i.parking_number %}" class="table-row" name="{{i.parking_number}}">
                      <td style="text-align:center">{{i.parking_number}}</td>
                      <td style="text-align:center">{{i.parking_name}}</td>
                      <td style="text-align:center">{{i.res_state}}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div></br></br>
        {% endif %}
        {% include 'footer.html'%} 
      </div>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>

{% endblock %}

{% block script%}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=ce903cdfbeb38247132d86bac3923a8b"></script>
<script>
  // 1. 테이블 선택하면 해당 주차관리로 넘어감
  $(document).ready(function(){
    $(".table-row").on('click', function(){
      location.href = $(this).data('uri');
    });
  });
  // 1. 끝
  </script>
{% endblock %}

templates/common/mypage_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!doctype html>
<html lang="en">
  <!-- 토글 스위치 css -->
  <style>
    [type="checkbox"] {
      appearance: none;
      position: relative;
      border: max(2px, 0.1em) solid gray;
      border-radius: 2.25em;
      width: 3.25em;
      height: 1.75em;
      vertical-align: middle;
    }
    
    [type="checkbox"]::before {
      content: "";
      position: absolute;
      left: 0;
      width: 1.45em;
      height: 1.45em;
      border-radius: 50%;
      transform: scale(0.8);
      background-color: gray;
      transition: left 250ms linear;
    }
    
    [type="checkbox"]:checked {
      background-color: #3f51b5;
      border-color: #3f51b5;
    }
    
    [type="checkbox"]:checked::before {
      background-color: white;
      left: 1.5em;
    }
    
    [type="checkbox"]:disabled {
      border-color: lightgray;
      opacity: 0.7;
      cursor: not-allowed;
    }
    
    [type="checkbox"]:disabled:before {
      background-color: lightgray;
    }
    
    [type="checkbox"]:disabled + span {
      opacity: 0.7;
      cursor: not-allowed;
    }
    
    [type="checkbox"]:focus-visible {
      outline-offset: max(2px, 0.1em);
      outline: max(2px, 0.1em) solid tomato;
    }
    
    [type="checkbox"]:enabled:hover {
      box-shadow: 0 0 0 max(4px, 0.2em) lightgray;
    }
  </style>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      {% include 'navbar.html'%} 
      <div class="android-content mdl-layout__content">
        <a name="top"></a>
        </br>
        </br>
        <div class="android-be-customized-section mdl-typography--text-center" style="display:flex;justify-content:center;align-items:center;top:30%;">
          <div class="demo-card-wide mdl-card mdl-shadow--2dp" style="align-items:center; width:80%">
            <div class="mdl-card__title">
              <h2 class="mdl-card__title-text">주차공간 관리</h2></br>
            </div>
            <div class="mdl-card__supporting-text">
              현재 주차장 : {{parking_user.parking_name}}
              </br></br>
              예약가능여부
                <label class="" for="switch">
                  <input type="checkbox" id="switch" name="switch" class="mdl-switch__input" data-uri="{% url 'common:parking_modify' parking_user.parking_number %}">
                  <span class="mdl-switch__label"></span>
                </label></br></br>
              <div id="map" style="width:100%;height:350px;"></div>
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                </br>예약 현황</br>
              </div>
              <div style="width:100%; overflow:auto;">
                <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp" style="width:100%;">
                  <thead>
                    <tr>
                      <td style="text-align:center">예약시간</td>
                      <td style="text-align:center">시작시각</td>
                      <td style="text-align:center">종료시각</td>
                      <td style="text-align:center">차량번호</td>
                    </tr>
                  </thead>
                  <tbody>
                    {% for i in parking_res.all %}
                      <tr>
                        <td style="text-align:center">{{i.time}}</td>
                        <td style="text-align:center">{{i.start_time}}</td>
                        <td style="text-align:center">{{i.end_time}}</td>
                        <td style="text-align:center">{{i.res_car_number}}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        {% include 'footer.html'%} 
      </div>
    </div>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </body>
</html>

{% endblock %}

{% block script%}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=ce903cdfbeb38247132d86bac3923a8b"></script>
<script>
  // 1. 위도 경도 가져오기
  var lat = '{{parking_user.lat}}';
  var lon = '{{parking_user.lon}}';
  // 1. 끝
  
  // 2. 지도 출력
  var mapContainer = document.getElementById('map'), // 지도를 표시할 div
  mapOption = {
      center: new daum.maps.LatLng(lat, lon), // 지도의 중심좌표
      level: 5 // 지도의 확대 레벨
  };

  //지도를 미리 생성
  var map = new daum.maps.Map(mapContainer, mapOption);
  //마커를 미리 생성
  var marker = new daum.maps.Marker({
    position: new daum.maps.LatLng(lat, lon),
    map: map
  });
  // 2. 끝

  // 3. 예약상태 스위치로 나타내기
  var res_state = '{{parking_user.res_state}}';
  if(res_state=="ON"){
    $("#switch").prop("checked", true);
  } else{
    $("#switch").prop("checked", false);
  }
  // 3. 끝

  // 4. 예약상태 스위치 변경되면 DB에 반영하기
  $(document).ready(function(){
    $("#switch").change(function(){
      location.href = $(this).data('uri');
    })
  })
  // 4. 끝
</script>
{% endblock %}