common/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('mypage/', views.mypage, name='mypage'),
    path('mypage/<int:parking_number>/', views.mypage_detail, name="mypage_detail"),
    path('mypage/<int:parking_number>/modify/', views.parking_modify, name='parking_modify'),
    
    path('add/', views.add, name='add'),
    path('add/parking', views.parking_add, name='parking_add'),

    path('myreserve/', views.myreserve , name="myreserve"),
    path('myreserve/delete/<int:res_id>', views.myreserve_delete, name='myreserve_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from tayo import views

urlpatterns = [
    path('', views.main, name='main'),
    path("admin/", admin.site.urls),
    path("iot/", include('iot.urls')),
    path("tayo/", include('tayo.urls')),
    path('common/', include('common.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iot/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView

app_name = 'iot'

urlpatterns = [
    path('upload/', upload, name='upload'),
    path('sec_file/', SecFileListView.as_view(), name='list'),
    path('sec_file/<int:pk>', SecFileDetailView.as_view(), name='detail'),
]

tayo/urls.py
from django.urls import path
from .views import *
from django.views.generic import TemplateView
from . import views

app_name = 'tayo'

urlpatterns = [
    path('main/', views.main, name='main'),

    path('reserve/', views.reserve, name='reserve'),
    path('reserve/add', views.reserve_add, name='reserve_add'),

    path('info/', views.info, name='info'),
    path('parking/', views.parking, name='parking'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Introducing Lollipop, a sweet new take on Android.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <meta http-equiv="Expires" content="0"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <title>TayoTayo</title>

    <!-- Page styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.min.css">
    
    <!-- 기존 link -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <!-- Favicon -->
    <link rel="icon" href="../../static/images/logo_vector.svg">
    
</head>
<body>
    


<!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- jQuery JS -->
<script src={% static 'jquery-3.6.1.min.js' %}></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<!-- Bootstrap JS -->
{% block script %}{% endblock %}
</body>
</html>

templates/footer.html
<footer class="android-footer mdl-mega-footer">
    <div class="mdl-mega-footer--top-section">
      <div class="mdl-mega-footer--right-section">
        <a class="mdl-typography--font-light" href="#top">
          Back to Top
          <i class="material-icons">expand_less</i>
        </a>
      </div>
    </div>

    <div class="mdl-mega-footer--middle-section">
      <p class="mdl-typography--font-light">[멀티캠퍼스] 프로젝트형 3개 과정 융복합 프로젝트 1조 타요타요</p>
      <p class="mdl-typography--font-light"></p>
    </div>

    <div class="mdl-mega-footer--bottom-section">
      <a class="android-link android-link-menu mdl-typography--font-light" id="BigData-dropdown">
        BigData
        <i class="material-icons">arrow_drop_up</i>
      </a>
      <ul class="mdl-menu mdl-js-menu mdl-menu--top-left mdl-js-ripple-effect" for="BigData-dropdown">
        <li class="mdl-menu__item">김준호</li>
        <li class="mdl-menu__item">정수연</li>
      </ul>
      <a class="android-link android-link-menu mdl-typography--font-light" id="IoT-dropdown">
        IoT
        <i class="material-icons">arrow_drop_up</i>
      </a>
      <ul class="mdl-menu mdl-js-menu mdl-menu--top-left mdl-js-ripple-effect" for="IoT-dropdown">
        <li class="mdl-menu__item">배민지</li>
      </ul>
      <a class="android-link android-link-menu mdl-typography--font-light" id="Cloud-dropdown">
        Cloud
        <i class="material-icons">arrow_drop_up</i>
      </a>
      <ul class="mdl-menu mdl-js-menu mdl-menu--top-left mdl-js-ripple-effect" for="Cloud-dropdown">
        <li class="mdl-menu__item">김도현</li>
        <li class="mdl-menu__item">구경선</li>
        <li class="mdl-menu__item">송경진</li>
        <li class="mdl-menu__item">이재원</li>
      </ul>
      <a class="android-link mdl-typography--font-light" href="">Blog</a>
      <a class="android-link mdl-typography--font-light" href="">GitHub</a>
    </div>

  </footer>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<div class="android-header mdl-layout__header mdl-layout__header--waterfall">
    <div class="mdl-layout__header-row">
      <span class="android-title mdl-layout-title">
        <img class="android-logo-image" href="{% url 'tayo:main'%}" src="/static/images/logo.png" style="object-fit:cover; height:100%;">
      </span>
      <!-- Add spacer, to align navigation to the right in desktop -->
      <div class="android-header-spacer mdl-layout-spacer"></div>

      <!-- Navigation -->
      <div class="android-navigation-container">
        <nav class="android-navigation mdl-navigation">
            <a class="mdl-navigation__link" style="text-decoration-line:none;" href="{% url 'tayo:main'%}">홈</a>
            <a class="mdl-navigation__link" style="text-decoration-line:none;" href="{% url 'tayo:info'%}">이용방법</a>
            <a class="mdl-navigation__link" style="text-decoration-line:none;" href="{% url 'tayo:reserve'%}">예약하기</a>
            <a class="mdl-navigation__link" style="text-decoration-line:none;" href="{% url 'tayo:parking'%}">주차장현황</a>
            <button style="background-color:white;" class="android-more-button mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect" id="more-button">
                <i class="material-icons">person</i>
            </button>
            <ul class="mdl-menu mdl-js-menu mdl-menu--bottom-right mdl-js-ripple-effect" for="more-button">
                {% if user.is_authenticated %}
                  <a class="mdl-menu__item" href="{% url 'common:mypage'%}">마이페이지</a>
                  <a class="mdl-menu__item" href="{% url 'common:myreserve'%}">나의예약</a>
                  <a class="mdl-menu__item" href="{% url 'common:logout'%}">로그아웃</a>
                {% else %}
                  <a class="mdl-menu__item" href="{% url 'common:login'%}">로그인</a>
                {% endif %}
            </ul>
        </nav>
      </div>
      <span class="android-mobile-title mdl-layout-title">
        <img class="android-logo-image" src="/static/images/logo.png" style="object-fit:cover; height:100%;">
      </span>
      
    </div>
</div>

<div class="android-drawer mdl-layout__drawer">
    <span class="mdl-layout-title" style='background-color:#82B7F9;'>
    </span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="{% url 'tayo:main'%}">홈</a>
      <a class="mdl-navigation__link" href="{% url 'tayo:info'%}">이용방법</a>
      <a class="mdl-navigation__link" href="{% url 'tayo:reserve'%}">예약하기</a>
      <a class="mdl-navigation__link" href="{% url 'tayo:parking'%}">주차장현황</a>
      <a class="mdl-navigation__link" href="#"></a>
      {% if user.is_authenticated %}
        <a class="mdl-navigation__link" href="{% url 'common:mypage'%}">마이페이지</a>
        <a class="mdl-navigation__link" href="{% url 'common:myreserve'%}">나의예약</a>
        <a class="mdl-navigation__link" href="{% url 'common:logout'%}">로그아웃</a>
      {% else %}
        <a class="mdl-navigation__link" href="{% url 'common:login'%}">로그인</a>
      {% endif %}
    </nav>
    
</div>